### ISSUE TITLE
Incorrect layout on http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi page.

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#10]
See attachment for details
image 1 
![h1](https://f.cloud.github.com/assets/4744668/685093/5c2098d2-da18-11e2-9f68-6cc99dfef10f.png)
image 2
![h2](https://f.cloud.github.com/assets/4744668/685114/538664d4-da1a-11e2-9927-41fe61a091c7.png)

**Comment by phihnp** [comment]
Closed
