### ISSUE TITLE
Can't Upload File on http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi form

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#11]
1. login to system with admin level
2. Click "Đăng hình ảnh" to upload file = > popup form was shown
3. Choose file from computer  to upload
   Actual result 
   upload file is always "Đang xử lý" and not complete ( image )
   Expected result 
   It should allow user to upload file  successfully.
   ![untitled](https://f.cloud.github.com/assets/4744668/685259/ebfac77a-da22-11e2-9f4e-871ab4bc13b2.png)

**Comment by vinhleevizi** [comment]
error by: conflicts with plugin : disqus-recent-comments-widget. if we deactive plugin disqus-recent-comments-widget, upload image will to success!

**Comment by vinhleevizi** [comment]
Fixed.
