### ISSUE TITLE
[Fronend] - [articles by author ] : English language

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#12]
http://tremocoi.org.vn/author/admin :
Should replace English text by Vietnamese...
See the screenshot
![englishtext](https://f.cloud.github.com/assets/4744755/685288/17928e1c-da24-11e2-8391-0cb0c36c4a35.gif)

**Comment by hongnhan** [comment]
![englishtext_02](https://f.cloud.github.com/assets/4744755/685313/c3fac1a0-da25-11e2-835c-c924c8f65d9b.gif)

**Comment by hongnhan** [comment]
Please also fix the error above  at pagination box in pages : 
http://tremocoi.org.vn/category/tin-tuc
http://tremocoi.org.vn/category/su-kien
http://tremocoi.org.vn/category/nhung-tam-long-vang
http://tremocoi.org.vn/category/van-ban-luat-ve-tre-em

**Comment by phihnp** [comment]
fixed
