### ISSUE TITLE
[Search] Popup show incorrectly when click on "Tìm Kiếm' button and it didn't work on chrome

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#13]
Step 
1 Dont input anything on "Tìm kiếm " Textbox
2 Click "Tìm Kiếm" button
Actual result 
1.Notify Popup for Empty textbox didn't work on Chrome
2 It must use "VietNamese" langguage, dont' use "English" language in this popup=>please replace text "Please fill out this field" by "Vui lòng nhập từ khóa".
![untitled](https://f.cloud.github.com/assets/4744668/685332/0be10adc-da27-11e2-80e3-89bc799f6aa3.png)

**Comment by hieutran05** [comment]
Fixed, Please test

**Comment by thanhchau** [comment]
It still didn't work on Chrome ,  please take a look 
![untitled](https://f.cloud.github.com/assets/4744668/701183/e4595c8c-dd6c-11e2-900f-b0cbf046d236.png)

**Comment by hieutran05** [comment]
Make sure your browser has HTML5 supported

**Comment by thanhchau** [comment]
I am using Chrome 27.0.1453.116 m, it is latest version and has  HTML5 supported

**Comment by hieutran05** [comment]
Still working. Can you please test on other machines?

![screenshot from 2013-06-25 15 52 21](https://f.cloud.github.com/assets/4517325/701451/eb24528a-dd74-11e2-9765-a53dd4f425a9.png)

**Comment by thanhchau** [comment]
This issue is also happen on other machines. I have tested on "Hien"+"Chi Nhan" machines with the same version of Chrome and this bug is also happen. It also happen on Safari

**Comment by vinhleevizi** [comment]
Fixed.
