### ISSUE TITLE
[Search] Use Vietnamese language when raise message for empty result

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#14]
Step 
1. input keyword which not match with anything ( eg : keyword = "adsaDAASDABDKJB"
2. Click "Tìm Kiếm" button
=> Page "Kết quả tìm kiếm" was shown , please replace text "Sorry, no posts matched your criteria. " by Vietnamese language eg: "Không tìm thấy dữ liệu phù hợp với từ khóa....."
![untitled](https://f.cloud.github.com/assets/4744668/685353/4d1f98b4-da28-11e2-9343-e4752e023fbf.png)

it also happen when viewing author :  ( eg http://tremocoi.org.vn/author/hongnhan-nguyen )
![untitled](https://f.cloud.github.com/assets/4744668/694176/bc7d5a66-dca8-11e2-9024-55a8a85e7677.png)

**Comment by hieutran05** [comment]
modified. Please test

**Comment by thanhchau** [comment]
Click on this link http://tremocoi.org.vn/author/hongnhan-nguyen , it still met error , Language is still English
![untitled](https://f.cloud.github.com/assets/4744668/701202/72a3650a-dd6d-11e2-85e0-2fc640bf193f.png)

**Comment by hieutran05** [comment]
This ticket just mentions error on Search page. However, fixed on all pages. Please test
