### ISSUE TITLE
[Fronend] - [list posts] : excerpt is hidden 

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#15]
In list of posts page , i.e., http://tremocoi.org.vn/category/tin-tuc
excerpt is hidden when the title is so long.
Also check the error for other list posts pages.
![excerp_hidden](https://f.cloud.github.com/assets/4744755/685880/273bd7f2-da46-11e2-9579-d95b5a9f3897.gif)

**Comment by phihnp** [comment]
fixed
