### ISSUE TITLE
[Front-End] Checkbox " Tên mới" in page http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi is not show in Back-end

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#18]
In page " Nhập thông tin trẻ mồ côi" Checkbox " Tên mới is not show in Back-end
Goto page http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi 
1 Add New Tre Mo coi
2 Goto Admin site-> click on Tre Mo coi
=> Not have a field for "Ten Moi' on back-end, Please add
![untitled](https://f.cloud.github.com/assets/4744668/693369/48096dd4-dc83-11e2-83d5-e5a9a4e4f896.png)

**Comment by vinhleevizi** [comment]
fixed,
Please, test again.
