### ISSUE TITLE
[Fronend] - [Lien he ] : Captcha and submitting errors 

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#19]
1. Captcha and textbox are not aligned 
2. Leave textbox captcha empty -> submit : Display message: ban da nhap sai ma captcha
   => Expected result: display message : vui long nhap ma kiem tra
3. Input valid data => Submit => Error message: Thông điệp của bạn chuyển đi không thành công. Bạn vui lòng thử lại sau hoặc liên hệ với Quản trị website bằng phương thức khác.

4.Should limit number of inputted characters in some fields: Tên của bạn , 
Địa chỉ Email 
Điện thoại liên lạc
Tiêu đề
Thông điệp

**Comment by longnt** [comment]
1 -> fixed
2 -> error message and empty message are same in contact form 7 => result both: Bạn vui lòng nhập đúng mã CAPTCHA.
3 -> cannot connect email server (google mail). 
4-> email validate and phone number validate in contact form 7
