### ISSUE TITLE
Can't upload File on "http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi#"

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#20]
Step 
1. Goto Form "Nhập thông tin trẻ mồ côi"
2. Click "DaNg Hinh anh" to upload file
=> User can't upload file , popup was broken
![untitled](https://f.cloud.github.com/assets/4744668/693347/ceaade60-dc81-11e2-99cb-6175460765c3.png)

**Comment by dohaibac** [comment]
Related to Issue #11

**Comment by vinhleevizi** [comment]
Fixed.
Please. test agian.
Thanks!
