### ISSUE TITLE
[Back-End] "Người gặp trẻ" didn't show in Back-End. When user input Form "http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi" and Submit.

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#21]
Step
1. Goto Form "http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi" 
2. input data into all fields in Form
3. Click "Đăng Ký" to submit data
4. Goto admin site "http://tremocoi.org.vn/wp-admin/edit.php?post_type=tre-mo-coi"
5. Click to Edit the record which has just submit form front-end
=> "Người gặp trẻ" is always blank and not have data submit from Front-end.
![untitled](https://f.cloud.github.com/assets/4744668/693875/7ecfdaae-dc9e-11e2-9933-cd2ab04bf2ca.png)

**Comment by phihnp** [comment]
fixed
