### ISSUE TITLE
[Fronend] - [Don nhan yeu thuong] : Errors

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#23]
1. Should validate captcha (required field) at the same time with other required fields
   ![don nhan yeu thuong_validatecaptcha](https://f.cloud.github.com/assets/4744755/694018/cb40a238-dca3-11e2-9ab3-b0fe11603685.gif)
2. After submitting successfully, click back button in browser,  the captcha image is not reloaded.
3. Information Don nhan yeu thuong does not display in back end after user submitted successfully in fronend:  dia chi, Điện thoại di động, Điện thoại cố định, Nghề nghiệp ,Thu nhập,Giới tính.
4. Shoud validate Thu nhập be numeric
5. Hover over titles of fields : Họ tên , Email,... : pointer displays as hand => no links at these, so, should display point as normal (arrow) in this case.
   ![don nhan yeu thuong_pointer](https://f.cloud.github.com/assets/4744755/694148/fe2f65d6-dca7-11e2-872a-f3a035288073.gif)
6. leave Mã bảo mật blank, Click Dang ky button : Display: Mã bảo mật không đúng, vui lòng nhập lại. and editable fields are reset as initial values.
   => Expected result: Display message: Nhap ma bao mat + keep values user has inputted in editable fields.

**Comment by hant1011** [comment]
1. Should validate captcha (required field) at the same time with other required fields don nhan yeu thuong_validatecaptcha
   ===> OK
2. After submitting successfully, click back button in browser, the captcha image is not reloaded.
   ===> OK: Now the success message is shown at top of the form, so, don't have this case. Anyway, if another form you back by browser, it occurs by default of browser, can not fix this.
3. Information Don nhan yeu thuong does not display in back end after user submitted successfully in fronend: dia chi, Điện thoại di động, Điện thoại cố định, Nghề nghiệp ,Thu nhập,Giới tính.
   ===> I will do this soon.
4. Shoud validate Thu nhập be numeric 
   ===> OK
5. Hover over titles of fields : Họ tên , Email,... : pointer displays as hand => no links at these, so, should display point as normal (arrow) in this case. don nhan yeu thuong_pointer
   ===> I will assign this bug to Vinh or Long to help me about css. 
6. Leave Mã bảo mật blank, Click Dang ky button : Display: Mã bảo mật không đúng, vui lòng nhập lại. and editable fields are reset as initial values. => Expected result: Display message: Nhap ma bao mat + keep values user has inputted in editable fields.
   ===> When submiting wrong "Ma bao mat", system will show message and create a new "Ma bao mat" to more security. So need to clear the editable fields.

**Comment by hongnhan** [comment]
some issues have not fixed yet.Please inform if ok.

**Comment by hant1011** [comment]
Done:
[6/27/2013 9:20:25 AM] Nguyễn Thị Hồng Nhạn: thong tin bao chuc mung ban da dang ky
[6/27/2013 9:20:25 AM] Nguyễn Thị Hồng Nhạn: nhung o duoi van de error message
[6/27/2013 9:20:45 AM] Nguyễn Thị Hồng Nhạn: sau khi dang ky ok, thi ko reset ma bao mat lai
[6/27/2013 9:20:58 AM] Nguyễn Thị Hồng Nhạn: va co the de nguyen form do, submit di nhieu lan
And 1, 2, 4, 6

Waiting:

Information Don nhan yeu thuong does not display in back end after user submitted successfully in fronend: dia chi, Điện thoại di động, Điện thoại cố định, Nghề nghiệp ,Thu nhập,Giới tính.
===> I will do this soon.

Hover over titles of fields : Họ tên , Email,... : pointer displays as hand => no links at these, so, should display point as normal (arrow) in this case. don nhan yeu thuong_pointer
===> I will assign this bug to Vinh or Long to help me about css.

**Comment by hongnhan** [comment]
ok except items of waiting...

**Comment by longnt** [comment]
Hover over titles of fields : Họ tên , Email,... : pointer displays as hand => no links at these, so, should display point as normal (arrow) in this case. don nhan yeu thuong_pointer
===> I will assign this bug to Vinh or Long to help me about css.
-> fixed, please check again. Thanks.

**Comment by hongnhan** [comment]
"Hover over titles of fields : Họ tên , Email," -> Tested.
