### ISSUE TITLE
Link active of new account not enough to identify 

### ISSUE THREAD

**Issue by phuongchi279** [dohaibac/Tre_mo_coi#24]
Link kích hoạt sau khi đăng ký account: http://tremocoi.org.vn?userlogin=Phuong Chi&activation_key=abbf6d267b8553d3
Hệ thống nhận diện link tới http://tremocoi.org.vn?userlogin=Phuong
Actual: 
- User click link "http://tremocoi.org.vn?userlogin=Phuong"show message "Bạn cần kích hoạt tài khoản tại hòm thư điện tử của bạn, trước khi sử dụng chức năng này. Bạn có muốn nhận lại thư kích hoạt tài khoản không?"
  ![login sau khi da kich hoat tai khoan](https://f.cloud.github.com/assets/4798167/694218/251e9e44-dcaa-11e2-8ef1-013f539ef224.png)
  Expect: 
- Hệ thống nhận diện đầy đủ link 
- Yêu cầu user không có các ký tự trắng trong account

**Comment by dinhhientran** [comment]
Hi chị,

Thật ra nếu tên đăng nhập có khoảng trắng là không hợp lệ, e có bổ sung việc validate username khi đăng ký rồi. Chị  check lại nhé.

Regards,
Hien.

**Comment by phuongchi279** [comment]
Fixed
