### ISSUE TITLE
[Front-end]-[Footer] Popup should show when user Click to sharing Facebook, Twiter or Google Plus

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#27]
Currently when user click to share Facebook on Footer it let user to Facebook site and when user click cancel sharing , it didn't return to http://tremocoi.org.vn/ site . 
Expected result : 
It should show popup to sharing once user click to cancel sharing or Sharing complete , it must return to http://tremocoi.org.vn/ site
![untitled](https://f.cloud.github.com/assets/4744668/694496/7aa83f44-dcb1-11e2-8586-9a8a75c8e776.png)

Notes : it should show Popup sharing in case Sharing Twiter , Google Plus too.

Referces site : http://www.mysexulator.com/ ( popup sharing )
![untitled](https://f.cloud.github.com/assets/4744668/694477/19a0bb40-dcb1-11e2-8ab9-d45c575ad813.png)

**Comment by longnt** [comment]
facebook should link to fan page. The same for twitter and google+ (comming soon)
