### ISSUE TITLE
Textarea can narrow

### ISSUE THREAD

**Issue by phuongchi279** [dohaibac/Tre_mo_coi#28]
Actual : All Textarea can narrow
EXpect : Disable narrow of textarea
![narrow](https://f.cloud.github.com/assets/4798167/694739/d5deb30a-dcb8-11e2-9d2c-01e808344367.jpg)

**Comment by hant1011** [comment]
Help me to fix this bug, Vinh!
Thanks!

**Comment by vinhleevizi** [comment]
Fix :
1. sizie textarea on page: http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi
2. position captcha on page: http://tremocoi.org.vn/don-nhan-yeu-thuong

Please, test again!

**Comment by phuongchi279** [comment]
Fixed
