### ISSUE TITLE
[Fronend] - [Paging] : Nothing happens when user clicks on number

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#29]
![paging_nothinghappens](https://f.cloud.github.com/assets/4744755/700301/2d74116c-dd42-11e2-9010-164496d183db.gif)
Please also  fix the error above for other pages, such as:
http://tremocoi.org.vn/category/tin-tuc
http://tremocoi.org.vn/category/su-kien
http://tremocoi.org.vn/category/nhung-tam-long-vang
http://tremocoi.org.vn/category/chuong-trinh-hoat-dong
http://tremocoi.org.vn/category/van-ban-luat-ve-tre-em

**Comment by hieutran05** [comment]
Fixed
