### ISSUE TITLE
Site http://tremocoi.org.vn/ didn't  work  on IE 8

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#3]
Site http://tremocoi.org.vn/ didn't  work  on IE  8
- Layout of home page and other page are Broken

**Comment by longnt** [comment]
hi a Vinh, check giúp em cái ie ^^!

**Comment by vinhleevizi** [comment]
vinh mới fix lại. Châu check nhé!

**Comment by thanhchau** [comment]
Still dont' working on IE 8

**Comment by dohaibac** [comment]
please don't check in IE8, it really low priority.
