### ISSUE TITLE
Back-End: The content of "Tre mo coi" doesn't show fully

### ISSUE THREAD

**Issue by lancao** [dohaibac/Tre_mo_coi#30]
Steps: 
1. Go to Tre mo coi section 
2. Click on Edit link
3. Click View link
Actual result : The content doesn't show fully
Expected result: The content should be shown fully
Note: In "Nhan con nuoi" section, the content just shows "Li do nhan con nuoi" when user clicks on View--> It should show all information of "Nhan con nuoi " section.
See screenshot: 
![the_content_should_be_shown_fully](https://f.cloud.github.com/assets/4811444/700439/50f687bc-dd49-11e2-91ab-e9899b3704ac.png)

**Comment by longnt** [comment]
these content are private. only admin can show them on backend
