### ISSUE TITLE
[Đón nhận yêu thương] UI have problem 

### ISSUE THREAD

**Issue by phuongchi279** [dohaibac/Tre_mo_coi#32]
![don nhan yeu thuong](https://f.cloud.github.com/assets/4798167/701648/5ce61638-dd7a-11e2-97a8-1e3731517d26.jpg)
1. Message after validate xuất hiện xa với ô textbox 
2. Điện thoại di động & điện thoại cố định chưa có TEMP cho user nhập
3. Thu nhập chưa phân cách giá trị (VD 1.000.000)
4. Textarea chưa thẳng hàng với các textbox phía trên

![nhu cau](https://f.cloud.github.com/assets/4798167/701682/19d8eea0-dd7b-11e2-8985-d2c25100b079.jpg)
1. Dropdown list quá lớn.Khaong cách từ 2013 tới icon Down quá rộng 
2. Mã bảo mật không thẳng hàng với textbox mã bảo mật

**Comment by longnt** [comment]
first image
1 => fixed
2 => it will be validated after input value
3 => it is number value
4 => fixed
second image
1 => fixed
2 => fixed
please check again. Thanks

**Comment by phuongchi279** [comment]
first image
1 => fixed 
QA : verified

2 => it will be validated after input value
QA : Điện thoại di động & điện thoại cố định chưa có TEMP cho user nhập

3 => it is number value
QA : Thu nhập chưa phân cách giá trị (VD 1.000.000)

4 => fixed
QA : verified

second image
1 => fixed 
QA : verified
2 => fixed
QA : verified
please check again. Thanks

**Comment by longnt** [comment]
2 => temp add on placeholder
3=> fixed
please check again. Thanks.

**Comment by phuongchi279** [comment]
Verified
