### ISSUE TITLE
[Liên hệ]Show message but on form don't have position warning 

### ISSUE THREAD

**Issue by phuongchi279** [dohaibac/Tre_mo_coi#33]
Show message but on form don't have position warning. User can not know WHY error
![lien he](https://f.cloud.github.com/assets/4798167/701818/ff5edce8-dd7e-11e2-89c0-2242e46c30cc.jpg)

**Comment by longnt** [comment]
this error message show when website backend can not connect smtp mail server.

**Comment by longnt** [comment]
i changed error message to "Thông điệp của bạn chuyển đi không thành công. Có thể do server mail của chúng tôi không hoạt động.  Bạn vui lòng thử lại sau hoặc liên hệ với Quản trị website bằng phương thức khác."

**Comment by phuongchi279** [comment]
Fixed
