### ISSUE TITLE
[Front end] - click don nhan yeu thuong, nhap thong tin tre mo coi without login

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#34]
1. Click on Don nhan yeu thuong, Nhap thong tin tre menu or buttons in right sidebar without login
2. Display popup login -> Login the system .
   Result: After login, the system takes user to home page
   Expected result: After login, the system takes user to the page corresponding to the button user has clicked. (don nhan yeu thuong page, nhap thong tin tre page)

**Comment by longnt** [comment]
fixed. please check again. Thanks.

**Comment by hongnhan** [comment]
please also fix the error above for login with facebook, twitter, gmail
