### ISSUE TITLE
[Văn bản luật trẻ em]No comment display on facebook. 

### ISSUE THREAD

**Issue by phuongchi279** [dohaibac/Tre_mo_coi#35]
Step
1. Open 1 news on "Văn bản luật trẻ em"
2. Click "Like"
Actual
1. Show dialog to post comment
2. Enter content in to textarea "Viet bình luận"
3. Click "Đăng lên facebook"
Expect
1. No comment display on facebook.

**Comment by longnt** [comment]
please check again. No issue when i tested. please don't unlike after click "đăng lên facebook"

**Comment by phuongchi279** [comment]
OKI
