### ISSUE TITLE
[Văn bản luật trẻ em]Message has shown by English language

### ISSUE THREAD

**Issue by phuongchi279** [dohaibac/Tre_mo_coi#36]
Step 
1. Login http://tremocoi.org.vn
2. Go to Trẻ Mồ Côi > Văn bản luật về trẻ em > Thủ tục nhận con nuôi
3. Post commetn
4. Click on Post-menu on right hand of comment 
5. Choose "Đánh dấu là không thích hợp"
Actual
Message has shown by English language
Expect 
Message has shown by VietNam language
![english vietnam](https://f.cloud.github.com/assets/4798167/707078/4fa21034-de0c-11e2-9fb8-d7de122a72fc.jpg)

**Comment by vinhleevizi** [comment]
This bug is message of disqus system. I logined in discus website http://tremocoidemo.disqus.com , but i don't see setting to custom message when user Choose "Đánh dấu là không thích hợp".
Please, confirm this bug with PM of project.
Thanks!
