### ISSUE TITLE
[Back-End]-[Bai viet]: Can't insert an image in a post by "Thu vien" or Editor

### ISSUE THREAD

**Issue by lancao** [dohaibac/Tre_mo_coi#37]
Error 1: Can't insert an image by Thu vien: 
 Steps:
1. Click on a post in "Bai viet" section
2. Click on "Thu vien" button to insert an image
3. Click Upload File
4. Select an image
5. Click on 'Create a gallery' button
Actual result: The text "[gallery ids="594,596"]" is shown in this post in "Tin tuc" list
Expected result: The text should be hidden
See screenshot
![insert_image_by_thu_vien](https://f.cloud.github.com/assets/4811444/707279/88d5f0b6-de14-11e2-979f-312662b73cfc.png)
Error 2: Can't insert an image by Editor
Steps:
1. Click on a post in "Bai viet" section
2. Click on NextGEN.des icon on Editor to insert an image
3. Select an image from Album
4. Click on "Chen` " button
Actual result: The text "[singlepic id=67 w=320 h=240 float=]" is shown in this post in "Tin tuc" list
Expected result: The text should be hidden and the image should be inserted succesfully
See screen
![insert_image_by_editor](https://f.cloud.github.com/assets/4811444/707307/2ed16450-de15-11e2-9fb7-52fbc4b5ad91.png)
shot:

**Comment by phihnp** [comment]
fixed

**Comment by hongnhan** [comment]
tested.
