### ISSUE TITLE
[Back-End]-[Tre mo coi]: The layout is broken 

### ISSUE THREAD

**Issue by lancao** [dohaibac/Tre_mo_coi#38]
When admin adds or edits a post in "Tre mo coi" section, he notices that the layout is broken.
See screenshot: 
![broken_layout_in_admin](https://f.cloud.github.com/assets/4811444/707427/94a82a8e-de1a-11e2-98e9-b23333154d26.png)

**Comment by vinhleevizi** [comment]
fixed.
Please, tets again. Thanks.
