### ISSUE TITLE
[Font-End] User name of User displayed in right corner is different between Profile page and Other page

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#39]
Currently in Profile Page , user name in right corner displayed by "Tên hiển thị" field 
But in other pages user name in right corner displayed by "Họ" + "Tên". 
Please using unified username displayed in right corner . Suggest using "Tên hiển thị" field
see image 1 & 2 for details
![untitled](https://f.cloud.github.com/assets/4744668/707912/4620e900-de33-11e2-8060-c3cd65132003.png)
![untitled](https://f.cloud.github.com/assets/4744668/707914/6ed593f0-de33-11e2-8310-1c1e900bbc26.png)

**Comment by longnt** [comment]
fixed. please test again. Thanks
