### ISSUE TITLE
[Front-End] Both "Bai Viet" and "Tre Mo Coi" are displayed in Search Result and paging in search result is very slowly

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#40]
Step
1. input keyword into Search textbox ( eg : keyword  = ''Hoang hieu anh"
2. Click "Tìm Kiếm" button to search
=> - Both "Bai Viet" and "Tre Mo Coi" are displayed in Search Result . 
     - Paging in search result is very slowly when clicking on number of page or next , previous,
Expected Result :
-  It should display only "Bai Viet" and don't need display information about "Tre Mo Coi
- Please improve performance of paging.

![untitled](https://f.cloud.github.com/assets/4744668/708384/3c8bf06e-de43-11e2-87eb-ebc52a305e55.png)

**Comment by dohaibac** [comment]
Hi Hieu, please fix for search result. About page loading slow, it because server run slowly. We will move to other hosting when we complete and have more visitor.

**Comment by longnt** [comment]
fixed. Please check again. Thanks
