### ISSUE TITLE
[Front end] - [Comment] - Message in English after the duplicate comment  has been posted.

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#41]
![comment_english](https://f.cloud.github.com/assets/4744755/719817/596f8ba2-df9a-11e2-8497-b25ec5eaeff4.gif)

**Comment by vinhleevizi** [comment]
This bug is message of disqus system. I logined in discus website http://tremocoidemo.disqus.com , but i don't see setting to custom message when user comment with duplicate content.
Please, confirm this bug with PM of project.
Thanks!
