### ISSUE TITLE
[Front-End]-[Nhap Thong Tin Tre] After Click "OK" on alert popup , user still click on "Đăng Ký" button

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#42]
Step :
1 Go to Form "Nhap Thong Tin Tre'.
2 Input all information
3 Click "Đăng Ký"
=> Alert popup "Nhập Dữ Liệu Thành Công" was shown , 
4 Click on "OK" button 
=> user still can click on "Đăng Ký" button again
It must lock current screen or redirect to other page immediately when "Nhap Thong Tin tre" complete.
![untitled](https://f.cloud.github.com/assets/4744668/719882/22b233a8-df9f-11e2-8d7e-6f0a0ee330cd.png)

**Comment by phihnp** [comment]
fixed

**Comment by thanhchau** [comment]
This bug still happen
