### ISSUE TITLE
[Front end] - [Tre mo coi navigate path] - Should use vietnamese language for tooltip of tre mo coi

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#43]
1. ![tremocoi_tooltip](https://f.cloud.github.com/assets/4744755/720707/f7712ed6-dfc8-11e2-9525-354cb18b353a.gif)
2. Category 
   ![tremocoi_tooltip2](https://f.cloud.github.com/assets/4744755/720766/331ea9b2-dfca-11e2-80c1-e779bec068e8.gif)
   Please fix item 2 for all categories(Tin tuc , su kien, nhung tam long vang, chuong trinh hoat dong, van ban luat, dia chi cac trung tam,...)

**Comment by longnt** [comment]
fixed.
please check again.
Thanks.

**Comment by dohaibac** [comment]
checked
