### ISSUE TITLE
[Front-End]There have a link "Tất Cả" on search result list, but it didn't work 

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#44]
Step
1 Input Keyword into Search textbox ( eg keyword = hoang hieu anh
2 Click Tim Kiem button
=> There have a link "Tất Cả" on search result list, but it didn't work
Expected result :
The link should be working when clicking or Remove it if it unnecessary
![search](https://f.cloud.github.com/assets/4744668/720808/b60b7c78-dfcb-11e2-9d14-2766219d7136.gif)

**Comment by dohaibac** [comment]
hi Hieu, please remove this link, using text only in here

**Comment by vinhleevizi** [comment]
fixed
