### ISSUE TITLE
[UI_Trang chủ]Sort and display at Tin tức, sự kiện

### ISSUE THREAD

**Issue by phuongchi279** [dohaibac/Tre_mo_coi#45]
![khoang cach](https://f.cloud.github.com/assets/4798167/734556/1572e190-e2d0-11e2-971b-c3c6e4388380.jpg)
Column 1 : 
- Khoảng cách giữa các ảnh không đồng đều : chỗ ghần chỗ xa
- 1 khoảng trống cuối cùng có thể add được thêm 1 ảnh nữa nhưng hiện tại đang BLANK
- Size ảnh ko đồng đều
  Column 2: 
- Ngày update ko cần show. Hoặc nếu show thì sẽ show ngày update cuối cùng hoặc ngày tạo. Plz confỉm PM

**Comment by dohaibac** [comment]
Please show only 5 title on the right column, show the created date at the end of title.
On the left column, fill text on the blank, under the image. 
All image not need have same size, only need the same width.

**Comment by phihnp** [comment]
fixed

**Comment by phuongchi279** [comment]
Verified OK, 
PLZ Fix all image  of "Chương trình hoạt động " are same width with "Tin tức - Sự kiện"

**Comment by phihnp** [comment]
fixed

**Comment by vinhleevizi** [comment]
Please, test again.
Thanks!
