### ISSUE TITLE
[Front end] - View a post: should format datetime again

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#5]
1. View a post, i.e., http://tremocoi.org.vn/am-ap-tinh-me-nuoi-cua-nhung-dua-tre-bat-hanh.html
   Result: Datetime displays in page:  Tháng Sáu 18th, 2013 bởi admin
   Expected result: Should format date time in Vietnamese cultural :Ngày 18 Tháng 6 Năm 2013 or : 18/6/2013

**Comment by phihnp** [comment]
Closed

**Comment by phihnp** [comment]
fixed
