### ISSUE TITLE
[Back end] - [edit a post] - can not upload image

### ISSUE THREAD

**Issue by hongnhan** [dohaibac/Tre_mo_coi#6]
In admin : chinh sua bai viet -> Dat anh tieu bieu -> Upload files -> chon tap tin -> Upload
Result : display error message
See the screenshot
![uploadimage_error](https://f.cloud.github.com/assets/4744755/680457/6eea5a62-d990-11e2-8a66-3919b89e6c89.gif)

**Comment by phihnp** [comment]
fixed
