### ISSUE TITLE
[Chrome-IE] Error in RSS function 

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#8]
Step 
1 Goto Home Page ( using chrome or IE )
2 Move to Footer section
3 Click on RSS icon on Footer to Feed
===> Error page was met . See Image for Details
![rss_error](https://f.cloud.github.com/assets/4744668/680539/7d8cd1c8-d993-11e2-9016-8572a2374916.png)

**Comment by vinhleevizi** [comment]
Fix display rss on browser chrome and IE.

**Comment by thanhchau** [comment]
It still met error on IE 9 , please check again

**Comment by vinhleevizi** [comment]
fixed.
Please, test again.
Thanks
