### ISSUE TITLE
In page http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi, "Ngày sinh *" is required field , but don't input anything into "Ngày sinh *" user  still can submit information

### ISSUE THREAD

**Issue by thanhchau** [dohaibac/Tre_mo_coi#9]
Step 
1. Goto page http://tremocoi.org.vn/nhap-thong-tin-tre-mo-coi
2. Input any information except "Ngày sinh *"
3. Click "Đăng Ký"
Actual result :
-"Ngày sinh *" is required field but don't input anything into "Ngày sinh *" , user  still can submit information.
Expected result
Need validate required for "Ngày sinh *"
See attach Image 
![untitled](https://f.cloud.github.com/assets/4744668/685028/e04693f4-da14-11e2-98ea-50ad400bca7c.png)

**Comment by phihnp** [comment]
Closed
